<?php
// ─────────────────────────────────────────────────────────────────────────────
// dash_config.php  ·  Server Homepage Dashboard — generated by setup wizard
// ─────────────────────────────────────────────────────────────────────────────
// This file is overwritten by setup.php when you run the setup wizard.
// If you are locked out after an upgrade, delete this file and visit setup.php.
// ─────────────────────────────────────────────────────────────────────────────
define('DASH_SETUP_DONE', false);   // ← wizard will set this to true
define('DASH_USERNAME',      'admin');
define('DASH_PASSWORD_HASH', '');   // ← wizard fills in a real bcrypt hash
define('DASH_TITLE',         'Server Dashboard');
define('DASH_GRID_COLS',     3);
define('DASH_DB_TYPE',       'sqlite');
